  1 set tabstop=4                                                               
  2 set number
  3 set showcmd
  4 set cursorline
  5 set ignorecase
  6 set hlsearch
  7 set autoindent
  8 syntax on
  9 set title
 10 set sm
